version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip bash
            pip install docker-compose
      - run:
          name: Build docker-compose images
          command: docker-compose build
